import React from 'react';
import {
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  View,
} from 'react-native';
import Icon from '../atoms/Icon';
import ReceiptDetailGrid from '../molecules/ReceiptDetailGrid';
import ReceiptItemRow from '../molecules/ReceiptItemRow';
import ReceiptTotals from '../molecules/ReceiptTotals';
import ReceiptPoints from '../molecules/ReceiptPoints';

interface DownloadReceiptProps {
  visible: boolean;
  onClose: () => void;
  cart: any[];
  totalPrice: number;
  customerInfo: {
    name: string;
    phone: string;
    email: string;
    dob: string;
    pax: string;
  } | null;
  paymentProvider: string | null;
}

const DownloadReceipt = ({
  visible,
  onClose,
  cart,
  totalPrice,
  customerInfo,
  paymentProvider,
}: DownloadReceiptProps) => {
  if (!visible) return null;

  const totalQuantity = cart.reduce((sum, item) => sum + item.quantity, 0);

  // Dynamic calculations matching screenshot
  const discount5 = totalPrice * 0.05;
  const specialDiscount = 10.0;
  const surcharge15 = (totalPrice - discount5 - specialDiscount) * 0.15;
  const grandTotal = totalPrice - discount5 - specialDiscount + surcharge15;

  const displayName = customerInfo ? customerInfo.name : 'Valen';
  const displayPax = customerInfo && customerInfo.pax ? customerInfo.pax : '2';

  const orderId = `ORD${String(new Date().getTime()).slice(-10)}SR`;
  const orderDate = '13/11/25 • 20:00';

  const providerLabel = paymentProvider === 'stripe' ? 'Stripe' : paymentProvider === 'eftpos' ? 'EFTPOS' : paymentProvider === 'gpay' ? 'Google Pay' : 'Apple Pay';

  return (
    <View style={styles.container}>
      
      {/* HEADER CONTROL BAR */}
      <View style={styles.controlHeader}>
        <Pressable onPress={onClose} style={styles.backButton}>
          <Icon name="arrow-back" size={24} color="#171717" />
          <Text style={styles.backText}>Close Receipt</Text>
        </Pressable>
      </View>

      <ScrollView
        showsVerticalScrollIndicator={false}
        contentContainerStyle={styles.scrollContent}
      >
        <View style={styles.receiptPaper}>
          
          {/* Brand Header */}
          <Text style={styles.brandTitle}>SHINJUKU RAMEN</Text>
          <Text style={styles.brandAddress}>123 George St, Sydney NSW 2000, Australia</Text>

          <View style={styles.dashedSeparator} />

          {/* Details Table Molecule */}
          <ReceiptDetailGrid
            date={orderDate}
            orderId={orderId}
            customerName={displayName}
            pax={displayPax}
            paymentMethodLabel={providerLabel}
            paymentTime={orderDate}
            isThermalFormat={true}
          />

          <View style={styles.dashedSeparator} />

          {/* Order Header Number */}
          <Text style={styles.dineInTitle}>DINE IN - #001</Text>

          <View style={styles.dashedSeparator} />

          {/* Ordered Details List Molecules */}
          <View style={styles.itemsSection}>
            <Text style={styles.sectionTitle}>Order Details</Text>

            {cart.map((item) => (
              <ReceiptItemRow
                key={item.id}
                item={item}
                isThermalFormat={true}
              />
            ))}

            {/* Note */}
            <View style={styles.noteContainer}>
              <Text style={styles.noteTitle}>Note:</Text>
              <Text style={styles.noteText}>Please be hurry...</Text>
            </View>
          </View>

          <View style={styles.dashedSeparator} />

          {/* Totals Section Molecule */}
          <ReceiptTotals
            totalPrice={totalPrice}
            totalQuantity={totalQuantity}
            paymentMethodLabel={providerLabel}
            isThermalFormat={true}
          />

          <View style={styles.dashedSeparator} />

          {/* Points calculations Molecule */}
          {customerInfo && <ReceiptPoints />}

          {customerInfo && <View style={styles.dashedSeparator} />}

          {/* Receipt Footer */}
          <Text style={styles.receiptFooterText}>✜✜ Thank You ✜✜</Text>
          <Text style={styles.receiptFooterSubtext}>
            This document is a valid receipt generated by Shinjuku Ramen
          </Text>

        </View>
      </ScrollView>

    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#F5F5F5',
    zIndex: 1000,
  },

  controlHeader: {
    paddingTop: 45,
    height: 87,
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#EEEEEE',
  },

  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },

  backText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#171717',
  },

  scrollContent: {
    paddingVertical: 20,
    alignItems: 'center',
  },

  receiptPaper: {
    backgroundColor: '#FFFFFF',
    width: '90%',
    maxWidth: 360,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#EAEAEA',
  },

  brandTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#8B1D1D',
    textAlign: 'center',
    marginBottom: 4,
  },

  brandAddress: {
    fontSize: 11,
    color: '#A0A0A0',
    textAlign: 'center',
    marginBottom: 10,
  },

  dashedSeparator: {
    borderStyle: 'dashed',
    borderBottomWidth: 1,
    borderColor: '#CCCCCC',
    marginVertical: 12,
  },

  dineInTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#171717',
    textAlign: 'center',
  },

  itemsSection: {
    marginTop: 4,
  },

  sectionTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#666666',
    marginBottom: 10,
  },

  noteContainer: {
    marginTop: 6,
  },

  noteTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: '#171717',
    marginBottom: 2,
  },

  noteText: {
    fontSize: 12,
    color: '#555555',
  },

  receiptFooterText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#A0A0A0',
    textAlign: 'center',
    marginTop: 10,
    marginBottom: 4,
  },

  receiptFooterSubtext: {
    fontSize: 9,
    color: '#A0A0A0',
    textAlign: 'center',
  },
});

export default DownloadReceipt;
